'use client';
import {useEffect,useState} from 'react';
type Item={disco_track_id:string;source_row_number:number;candidate_kind:string;review_state:string;title:string;artist:string;format:string};
type Queue={source:string|null;total:number;items:Item[];totals?:{total:number}};
type ApiError={error:string;detail?:string};
export default function FullmixKutReviewq(){
 const[q,setQ]=useState<Queue|null>(null),[error,setError]=useState(''),[status,setStatus]=useState('');
 const load=async()=>{setError('');try{const r=await fetch('/api/admin/fullmix-kut-reviewq/queue');const body:Queue|ApiError=await r.json();if(!r.ok||!('items' in body))throw new Error(('detail'in body&&body.detail)||('error'in body&&body.error)||'Queue unavailable');setQ(body)}catch(e){setQ(null);setError(e instanceof Error?e.message:'Queue unavailable')}};
 useEffect(()=>{void load()},[]);
 async function materialize(){setStatus('Creating exact FullMix review items…');try{const r=await fetch('/api/admin/fullmix-kut-reviewq/materialize',{method:'POST'});const body=await r.json();setStatus(JSON.stringify(body,null,2));if(r.ok)void load()}catch{setStatus('Materialization request failed.')}}
 return <main className="min-h-screen bg-black p-8 text-stone-100"><h1 className="text-2xl font-black">FULLMIX KUT REVIEWQ</h1><p className="mt-2 text-stone-400">One private KUT review item per active FullMix Track ID. System identity never uses title; titles below are display-only. This does not classify KK, sK, or mK and does not publish anything.</p>{error?<section className="mt-5 rounded border border-amber-500 p-4 text-amber-200"><b>FullMix queue is unavailable.</b><p className="mt-2 text-sm">{error==='service_client_unavailable'?'Render is missing the server database credential. Existing inventory has not been deleted.':error==='not_found'?'Open this page with your existing owner access session.':error}</p><p className="mt-2 text-sm">No inventory was changed. This connection error does not change source acceptance or release approval.</p></section>:<><button className="mt-5 rounded bg-amber-300 px-4 py-2 font-bold text-black" disabled={!q} onClick={materialize}>Create FullMix KUT review items</button><pre className="mt-4 text-sm">{status}</pre>{q&&<><p className="mt-6">Active source: {q.source||'none'} · {q.total} review items</p><div className="mt-3 space-y-2">{q.items.map(i=><article key={i.disco_track_id} className="rounded border border-stone-700 p-3"><b>{i.title||'Untitled'}</b><br/><small>Track ID: {i.disco_track_id} · source row {i.source_row_number} · {i.artist} · {i.format} · {i.review_state}</small></article>)}</div></>}</>}</main>}
