import { createClient } from "@supabase/supabase-js";
import { NextRequest, NextResponse } from "next/server";
import { ADMIN_SESSION_COOKIE, trustedProtectedPreview, validAdminSession, validAdminToken } from "@/lib/admin/adminSession";
import { validate4peIntakeEvidence } from "@/lib/kkr/intakeEvidenceGate";
export const dynamic = "force-dynamic";
const LT_PIX_TRACK_ID="c5b9e589-2db5-41c6-a335-0e3ee7f1f43f", IN_PIX_TRACK_ID="94856625-a4a7-449b-99ac-730d7a39e7b9", LYRIC_SHA="9657508e03e3ecb35c3341525fb3b67039ca50999ee957c13dfbbe19e27e8ec3";
function authorized(r:NextRequest){const t=r.headers.get("x-admin-token")?.trim()||r.nextUrl.searchParams.get("token")?.trim();return trustedProtectedPreview()||validAdminToken(t)||validAdminSession(r.cookies.get(ADMIN_SESSION_COOKIE)?.value)}
function client(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL?.trim(),key=process.env.SUPABASE_SERVICE_ROLE_KEY?.trim()||process.env.GPMC_KUT_SUPABASE_SECRET_KEY?.trim();return url&&key?createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}):null}
export async function GET(r:NextRequest){if(!authorized(r))return NextResponse.json({error:"not_found"},{status:404});const s=client();if(!s)return NextResponse.json({error:"server_supabase_connection_not_configured"},{status:503});const q=await s.from("gpmx_admin_kkr_tpr_candidate_v1").select("method_notes,updated_at").eq("candidate_key","kkr-torn-memories-intake-map-v1").limit(1).maybeSingle();if(q.error)return NextResponse.json({error:"mapping_read_failed",detail:q.error.message},{status:502});const notes=(q.data?.method_notes as any)?.mapping_notes||null;return NextResponse.json({queue:[{id:0,queue_order:0,authority_title:"TORN MEMORIES",lt_track_id:LT_PIX_TRACK_ID,in_track_id:IN_PIX_TRACK_ID,writer_pattern_mode:"FULL_LYRIC_BLK_SISTER_PAIR",review_state:"PENDING_HUMAN_TPR",owner_directive:"Map full lyric BLKs before any candidate creation.",structure_notes:notes}]});}
export async function POST(r:NextRequest){if(!authorized(r))return NextResponse.json({error:"not_found"},{status:404});const b=await r.json().catch(()=>null) as {reviewState?:string;structureNotes?:string}|null;if(!b?.reviewState||!b.structureNotes)return NextResponse.json({error:"invalid_request"},{status:400});let notes:any;try{notes=JSON.parse(b.structureNotes)}catch{return NextResponse.json({error:"invalid_mapping_json"},{status:400})}const evidence={full_lyric_read:notes.full_lyric_read===true,lyric_authority_sha256:LYRIC_SHA,source_audio_sha256:"PENDING_PRIVATE_SOURCE_VERIFICATION",lt_pix_track_id:LT_PIX_TRACK_ID,in_pix_track_id:IN_PIX_TRACK_ID,blks:(notes.blks||[]).map((x:any)=>({id:x.id,lines:x.lines,vtp:{start_sec:x.vtpStart,end_sec:x.vtpEnd},intp:{start_sec:x.intpStart,end_sec:x.intpEnd},sister_pair_id:`${x.id}__SISTER_PAIR`,mgs:x.mgs}))};const gate=validate4peIntakeEvidence({intake_evidence:evidence});if(b.reviewState==="STRUCTURE_IDENTIFIED"&&!gate.passed)return NextResponse.json({error:"incomplete_4pe_intake_evidence",detail:gate.reasons.join(",")},{status:400});const s=client();if(!s)return NextResponse.json({error:"server_supabase_connection_not_configured"},{status:503});const update=await s.from("gpmx_admin_kkr_tpr_candidate_v1").upsert({candidate_key:"kkr-torn-memories-intake-map-v1",card_key:"TORN_MEMORIES__4PE_INTAKE_MAP",authority_title:"TORN MEMORIES",ii_type:"4PE_INTAKE_MAP",container_type:"INTERNAL",display_text:"Full lyric BLK mapping; not a review candidate.",form_key:"FULL_LYRIC_BLK_SISTER_PAIR",start_sec:0,end_sec:0,audio_path:"",review_state:"MAPPING_COMPLETE",evidence_state:"4PE_INTAKE_EVIDENCE_CAPTURED",source_relation:"LT_PIX_IN_PIX_MAPPING",source_track_ref:LT_PIX_TRACK_ID,source_vocal_track_id:LT_PIX_TRACK_ID,source_in_pix_track_id:IN_PIX_TRACK_ID,lyric_authority_sha256:LYRIC_SHA,method_notes:{mapping_notes:notes,intake_evidence:evidence},updated_at:new Date().toISOString()},{onConflict:"candidate_key"});if(update.error)return NextResponse.json({error:"mapping_persist_failed",detail:update.error.message},{status:502});return NextResponse.json({ok:true,evidence:gate});}
