import { createHash } from "node:crypto";
import { createClient } from "@supabase/supabase-js";
import { NextRequest, NextResponse } from "next/server";
import { trustedProtectedPreview, validAdminToken } from "@/lib/admin/adminSession";
export const runtime = "nodejs";
function client(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL?.trim(),k=process.env.SUPABASE_SERVICE_ROLE_KEY?.trim()||process.env.GPMC_KUT_SUPABASE_SECRET_KEY?.trim();return u&&k?createClient(u,k,{auth:{persistSession:false,autoRefreshToken:false}}):null}
function csv(t:string){let r:string[][]=[],a:string[]=[],v='',q=false;for(let i=0;i<t.length;i++){const c=t[i],n=t[i+1];if(c==='"'&&q&&n==='"'){v+='"';i++}else if(c==='"')q=!q;else if(c===','&&!q){a.push(v);v=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;a.push(v);if(a.some(x=>x.trim()))r.push(a);a=[];v=''}else v+=c}if(v||a.length){a.push(v);r.push(a)}const[h,...b]=r;return b.map(x=>Object.fromEntries(h.map((k,i)=>[k,x[i]||''])))}
function classify(name:string,album:string){const x=`${name} ${album}`.toLowerCase();if(/\b(instro|instrumental|instro only)\b/.test(x))return 'IN_PIX_CANDIDATE';if(/\bcover\b/.test(x))return 'HOLD_RIGHTS_OR_MASTER_VERIFICATION';return 'VOCAL_LT_PIX_CANDIDATE'}
export async function POST(req:NextRequest){if(!trustedProtectedPreview()&&!validAdminToken(req.headers.get('x-admin-token')))return NextResponse.json({error:'not_found'},{status:404});const form=await req.formData();const file=form.get('file');if(!(file instanceof File)||!file.name.toLowerCase().endsWith('.csv'))return NextResponse.json({error:'csv_file_required'},{status:400});const text=await file.text();const hash=createHash('sha256').update(text).digest('hex');const records=csv(text).map(x=>({disco_track_id:String(x['Track ID']||'').trim(),track_name:String(x['Track name']||'').trim(),album:String(x.Album||'').trim(),artist:String(x.Artist||'').trim(),isrc:String(x.ISRC||'').trim(),classification:classify(String(x['Track name']||''),String(x.Album||''))})).filter(x=>x.disco_track_id&&x.track_name);const totals=Object.fromEntries(['VOCAL_LT_PIX_CANDIDATE','IN_PIX_CANDIDATE','HOLD_RIGHTS_OR_MASTER_VERIFICATION'].map(k=>[k,records.filter(x=>x.classification===k).length]));const s=client();if(!s)return NextResponse.json({error:'service_client_unavailable'},{status:503});const imported=await s.from('gpm_stl_playlist_imports').upsert({source_name:'GPMx STL Playlist 09-08-26.csv',source_sha256:hash,totals},{onConflict:'source_sha256'}).select('id').single();if(imported.error)return NextResponse.json({error:'import_persist_failed',detail:imported.error.message},{status:502});const rows=records.map(x=>({...x,source_import_id:imported.data.id,last_seen_at:new Date().toISOString()}));const upsert=await s.from('gpm_stl_track_registry').upsert(rows,{onConflict:'disco_track_id',ignoreDuplicates:true});if(upsert.error)return NextResponse.json({error:'registry_persist_failed',detail:upsert.error.message},{status:502});return NextResponse.json({ok:true,total:records.length,totals,source:'GPMx STL Playlist 09-08-26.csv'});}
