export const holidays = {
  "new-years-day": {
    title: "New Year’s Day",
    line: "Begin again with hope, reflection, and renewal.",
    question: "What kind of beginning should this HUG carry?",
    paths: ["Fresh start", "Hope", "Reflection", "New beginning", "I believe in this year"],
  },
  "martin-luther-king-jr-day": {
    title: "Martin Luther King Jr. Day",
    line: "Honor courage, service, justice, and shared humanity.",
    question: "What should this remembrance hold?",
    paths: ["Courage", "Service", "Justice", "Hope", "Shared humanity"],
  },
  "valentines-day": {
    title: "Valentine’s Day",
    line: "Send love, devotion, longing, romance, or tenderness.",
    question: "What kind of love should this HUG carry?",
    paths: ["I love you", "I choose you", "Romance", "Longing", "Deep devotion"],
  },
  "presidents-day": {
    title: "Presidents’ Day",
    line: "Mark leadership, history, civic memory, and reflection.",
    question: "What kind of civic reflection fits?",
    paths: ["Leadership", "History", "Service", "Reflection", "Country"],
  },
  "st-patricks-day": {
    title: "St. Patrick’s Day",
    line: "Send luck, joy, friendship, celebration, and warmth.",
    question: "What kind of celebration fits?",
    paths: ["Good luck", "Joy", "Friendship", "Playful", "Celebrate"],
  },
  passover: {
    title: "Passover",
    line: "Send remembrance, freedom, family, blessing, and resilience.",
    question: "What should this Passover HUG carry?",
    paths: ["Freedom", "Family", "Blessing", "Resilience", "Remembering"],
  },
  easter: {
    title: "Easter",
    line: "Send hope, renewal, faith, spring, and family warmth.",
    question: "What kind of renewal should this HUG carry?",
    paths: ["Hope", "Renewal", "Faith", "Family warmth", "Spring joy"],
  },
  "earth-day": {
    title: "Earth Day",
    line: "Send care for nature, renewal, gratitude, and shared responsibility.",
    question: "What should this Earth Day moment hold?",
    paths: ["Nature", "Renewal", "Gratitude", "Care", "Shared responsibility"],
  },
  "administrative-professionals-day": {
    title: "Administrative Professionals Day",
    line: "Recognize the people who keep work moving.",
    question: "What kind of appreciation should this HUG carry?",
    paths: ["Thank you", "You keep this going", "Respect", "Team gratitude", "You matter here"],
  },
  "mothers-day": {
    title: "Mother’s Day",
    line: "Thank Mom with a focused music moment.",
    question: "What do you want Mom to feel?",
    paths: ["Thank you, Mom", "I love you, Mom", "You were there", "Family love", "Gentle gratitude"],
  },
  "memorial-day": {
    title: "Memorial Day",
    line: "Honor remembrance, sacrifice, gratitude, and quiet reflection.",
    question: "What kind of remembrance is needed?",
    paths: ["Remembrance", "Sacrifice", "Gratitude", "Quiet honor", "Never forgotten"],
  },
  "flag-day": {
    title: "Flag Day",
    line: "Mark country, memory, service, and civic reflection.",
    question: "What kind of civic feeling fits?",
    paths: ["Country", "Memory", "Service", "Reflection", "Home"],
  },
  "fathers-day": {
    title: "Father’s Day",
    line: "Send thanks, respect, love, pride, or memory for Dad.",
    question: "What do you want Dad to feel?",
    paths: ["Thank you, Dad", "I love you, Dad", "Respect", "Proud of you", "Missing Dad"],
    candidatePix: [
      "Life’s a Test — Brandon Howard",
      "That’s a Have To — Jade Lotzow",
      "Have-To duet — Jade & Aaron Lotzow",
      "That Empty Chair — Lloyd Miller",
      "No Mystery — Billy Harper",
    ],
  },
  juneteenth: {
    title: "Juneteenth",
    line: "Honor freedom, resilience, memory, and celebration.",
    question: "What should this HUG honor?",
    paths: ["Freedom", "Resilience", "Memory", "Celebration", "Hope"],
  },
  "independence-day": {
    title: "Independence Day",
    line: "Celebrate freedom, home, summer, family, and national pride.",
    question: "What kind of Fourth of July feeling fits?",
    paths: ["Freedom", "Home", "Summer", "Family", "Celebrate"],
  },
  "labor-day": {
    title: "Labor Day",
    line: "Honor work, rest, effort, family, and the close of summer.",
    question: "What kind of Labor Day moment fits?",
    paths: ["Rest", "Hard work", "Family time", "Summer close", "Gratitude"],
  },
  "grandparents-day": {
    title: "Grandparents Day",
    line: "Send love, memory, gratitude, and family roots.",
    question: "What should a grandparent feel?",
    paths: ["Thank you", "Family roots", "Your love stayed", "Memory", "I love you"],
  },
  "patriot-day": {
    title: "Patriot Day",
    line: "Honor remembrance, courage, service, and national grief.",
    question: "What kind of remembrance fits?",
    paths: ["Remembering", "Courage", "Service", "National grief", "Never forgotten"],
  },
  "rosh-hashanah": {
    title: "Rosh Hashanah",
    line: "Send reflection, blessing, renewal, and hope for the year ahead.",
    question: "What should the new year carry?",
    paths: ["Blessing", "Renewal", "Reflection", "Hope", "Family"],
  },
  "yom-kippur": {
    title: "Yom Kippur",
    line: "Send reflection, repair, forgiveness, and solemn care.",
    question: "What should this solemn moment hold?",
    paths: ["Reflection", "Repair", "Forgiveness", "Care", "Peace"],
  },
  "indigenous-peoples-day": {
    title: "Indigenous Peoples’ Day",
    line: "Honor memory, heritage, land, people, and respect.",
    question: "What should this observance hold?",
    paths: ["Respect", "Heritage", "Memory", "Land", "People"],
  },
  "columbus-day": {
    title: "Columbus Day",
    line: "Mark history, civic memory, travel, and reflection.",
    question: "What kind of historical reflection fits?",
    paths: ["History", "Travel", "Civic memory", "Reflection", "Country"],
  },
  halloween: {
    title: "Halloween",
    line: "Send playful, spooky, funny, dramatic, or mischievous moments.",
    question: "What kind of Halloween feeling fits?",
    paths: ["Spooky", "Playful", "Funny", "Dramatic", "Mischief"],
  },
  "dia-de-los-muertos": {
    title: "Día de los Muertos",
    line: "Honor memory, ancestors, love, color, and continuing bonds.",
    question: "Who or what should this remembrance honor?",
    paths: ["Ancestors", "Memory", "Continuing love", "Family", "Celebration"],
  },
  "veterans-day": {
    title: "Veterans Day",
    line: "Honor service, courage, gratitude, and sacrifice.",
    question: "What kind of thanks should this HUG carry?",
    paths: ["Thank you for serving", "Courage", "Honor", "Sacrifice", "Respect"],
  },
  thanksgiving: {
    title: "Thanksgiving",
    line: "Send gratitude, family warmth, home, memory, and togetherness.",
    question: "What kind of gratitude fits?",
    paths: ["Thankful for you", "Family warmth", "Home", "Togetherness", "Blessing"],
  },
  "black-friday": {
    title: "Black Friday",
    line: "Send playful energy, surprise, deals, gifting, and holiday kickoff.",
    question: "What kind of holiday kickoff fits?",
    paths: ["Surprise", "Playful", "Gift energy", "Holiday kickoff", "Big reveal"],
  },
  "giving-tuesday": {
    title: "Giving Tuesday",
    line: "Send generosity, purpose, gratitude, and support.",
    question: "What kind of giving moment fits?",
    paths: ["Generosity", "Purpose", "Support", "Gratitude", "Cause"],
  },
  "christmas-eve": {
    title: "Christmas Eve",
    line: "Send anticipation, tenderness, family warmth, faith, and wonder.",
    question: "What should Christmas Eve feel like?",
    paths: ["Wonder", "Tenderness", "Family warmth", "Faith", "Almost Christmas"],
  },
  christmas: {
    title: "Christmas",
    line: "Send joy, wonder, love, faith, nostalgia, or family warmth.",
    question: "What kind of Christmas feeling should this HUG carry?",
    paths: ["Joy", "Wonder", "Family warmth", "Nostalgia", "Love"],
  },
  hanukkah: {
    title: "Hanukkah",
    line: "Send light, resilience, family, blessing, and celebration.",
    question: "What should this Hanukkah HUG carry?",
    paths: ["Light", "Family", "Blessing", "Resilience", "Celebration"],
  },
  kwanzaa: {
    title: "Kwanzaa",
    line: "Send unity, culture, family, purpose, and celebration.",
    question: "What should this Kwanzaa HUG carry?",
    paths: ["Unity", "Culture", "Family", "Purpose", "Celebration"],
  },
  "new-years-eve": {
    title: "New Year’s Eve",
    line: "Send reflection, goodbye, hope, celebration, and new beginnings.",
    question: "What kind of year-end moment fits?",
    paths: ["Goodbye to this year", "Hope", "Celebrate", "Reflection", "New beginning"],
  },
} as const;

export type HolidaySlug = keyof typeof holidays;

export const holidayList = Object.entries(holidays).map(
  ([slug, holiday]) => ({
    slug,
    title: holiday.title,
    line: holiday.line,
  }),
);
